### ISSUE TITLE
Min version supported

### ISSUE THREAD

**Issue by Silvia4** [pavel163/FilledView#1]
Hi,
thanks for your library. I have a problem with minimum API supported, it works only with API 24 and later. It is possible to extend it to min API 22?
Thanks

**Comment by pavel163** [comment]
Hello, @Silvia4. 
This library must support 22 api. I will try to check it at the weekend. Maybe I need to update all dependecies

**Comment by Silvia4** [comment]
With API 22 and 23 it doesn't give any error, but the fillew view is not showing at all.
Thanks!

**Comment by pavel163** [comment]
I fix this issue. But now min API 19

**Comment by Silvia4** [comment]
Thanks Pavel, but now I have this error (and the suggestion doesn't work):

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 is also present at [androidx.core:core:1.1.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-55:19 to override.
```

**Comment by pavel163** [comment]
@Silvia4  Do you use androidX?

**Comment by Silvia4** [comment]
No, I don't use it. What do you suggest?

**Comment by pavel163** [comment]
I updated all dependencies in this library. I use androidx.appcompat:appcompat:1.0.0.  
Try to migrate androidX https://developer.android.com/jetpack/androidx/migrate
